// 추천 퀴즈 라이브러리 — 운영자가 「퀴즈 만들기」 시 첫 화면(미션 라이브러리 패턴).
//
// 사용 흐름:
//   1. 대상자 선택 (예: 군인·20대 초반)
//   2. 주제별 예시 퀴즈(5문항) 목록 — 체크박스 + 펼쳐서 미리보기
//   3. 체크한 주제마다 별도 퀴즈로 발행 (시작/종료일은 운영자가 설정)
//
// 데이터 구조:
//   audiences[] → topics[] → questions[]
//   question 은 QuizCreatePage 의 내부 문항 형태와 맞춤:
//     type: 'MULTIPLE' | 'OX' | 'SHORT'
//     question_text, options[](MULTIPLE), correctIndex(MULTIPLE),
//     oxAnswer(OX), shortAnswer(SHORT, 다짐형은 null),
//     award_mode('CORRECT_ONLY' 기본), grading_mode('AUTO'/'MANUAL'),
//     point, explanation·source·sampleAnswer (라이브러리 표시·운영자 참고용)
//
// ⚠️ 콘텐츠 출처는 본인이 2026-06-04 공공기관·학술지로 검증함.
//   해설·출처는 라이브러리(운영자)에서만 노출. 발행된 quiz_questions 에는 저장 안 함.
// ⚠️ 객관식 정답이 원본에선 전부 보기1 → 발행 시 보기 순서 셔플로 정답 위치 랜덤화.

const A = 'CORRECT_ONLY' // award_mode 기본(맞추면 지급)

// 객관식
const mc = (question_text, options, correctIndex, explanation, source, point = 10) => ({
  type: 'MULTIPLE', question_text, options, correctIndex,
  award_mode: A, grading_mode: 'AUTO', point, explanation, source,
})
// OX
const ox = (question_text, oxAnswer, explanation, source, point = 10) => ({
  type: 'OX', question_text, oxAnswer,
  award_mode: A, grading_mode: 'AUTO', point, explanation, source,
})
// 주관식(다짐·성찰형 — 정답 없음, 기본 운영자 수동채점 / 맞추면 지급)
const sa = (question_text, sampleAnswer, explanation, source, point = 10) => ({
  type: 'SHORT', question_text, shortAnswer: null,
  award_mode: A, grading_mode: 'MANUAL', point, explanation, source, sampleAnswer,
})

const TOPICS = [
  {
    key: 'smoking', title: '금연', emoji: '🚭', category: 'NO_SMOKING',
    questions: [
      mc('흡연이 군 체력평가와 관련해 나타낼 수 있는 영향으로 가장 적절한 것은?',
        ['3km 달리기 기록이 느려지고 팔굽혀펴기·윗몸일으키기 수행이 낮아질 수 있다', '심폐지구력과 전혀 관련이 없다', '단기간 흡연은 폐기능을 높인다', '흡연자는 운동 회복이 항상 더 빠르다'], 0,
        '군인 대상 연구에서 흡연자는 달리기 기록과 근력·근지구력 평가에서 불리한 경향이 보고되었습니다.',
        'https://doi.org/10.1155/2020/5968189'),
      ox('흡연은 피부 광노화를 촉진할 수 있으므로 피부 건강을 위해서도 금연이 중요하다.', 'O',
        '흡연은 피부 노화와 관련된 위험요인으로 설명됩니다.',
        'https://www.k-health.com/news/articleView.html?idxno=70596'),
      ox('궐련형 전자담배는 일반담배보다 유해물질이 없어 건강에 안전하다고 볼 수 있다.', 'X',
        '궐련형 전자담배도 유해성분과 발암물질이 보고되어 안전하다고 단정할 수 없습니다.',
        'https://www.khan.co.kr/article/201806072229005'),
      mc('금연 후 비교적 빠르게 나타나는 신체 변화로 가장 적절한 것은?',
        ['20분 후 혈압과 맥박이 정상화되는 방향으로 변한다', '폐기능은 10년이 지나야 처음 변한다', '금연 직후 산소 운반 능력은 반드시 악화된다', '금연 후 체력 회복은 불가능하다'], 0,
        '금연은 시간 경과에 따라 심혈관·호흡기 지표 회복에 도움이 됩니다.',
        'https://clinic.paju.go.kr/clinic/clinic_03/clinic_03_01/clinic_03_01_10.jsp'),
      sa('스트레스 때문에 흡연하고 싶을 때 사용할 수 있는 대체 행동을 2가지 적으세요.',
        '예: 심호흡, 짧은 산책, 물 마시기, 동료와 대화, 운동, 상담 요청',
        '군 장병 흡연 이유 중 스트레스 해소가 큰 비중을 차지하므로, 스트레스 대처 행동을 미리 정하는 것이 중요합니다.',
        'https://biz.heraldcorp.com/article/1916885'),
    ],
  },
  {
    key: 'alcohol', title: '절주', emoji: '🍺', category: 'ETC',
    questions: [
      mc('운동 후 음주가 근성장에 불리한 이유로 가장 적절한 것은?',
        ['단백질 합성을 낮추어 회복과 근성장을 방해할 수 있다', '근육 단백질 합성을 크게 증가시킨다', '수분 보충 효과가 커서 회복이 빨라진다', '비타민과 미네랄 손실을 막아준다'], 0,
        '음주 후 단백질 합성이 저하되어 운동 회복과 근성장에 불리할 수 있습니다.',
        'http://www.samsunghospital.com/home/healthInfo/content/contenView.do?CONT_CLS_CD=001021005003&CONT_ID=6352&CONT_SRC=HOMEPAGE&CONT_SRC_ID=33770'),
      ox('고농도 음주는 탈수와 호르몬 변화 등을 통해 근육 생성에 방해가 될 수 있다.', 'O',
        '알코올은 탈수와 테스토스테론 저하 등 운동 회복에 불리한 요인과 관련됩니다.',
        'http://www.samsunghospital.com/home/healthInfo/content/contenView.do?CONT_CLS_CD=001021005003&CONT_ID=6352&CONT_SRC=HOMEPAGE&CONT_SRC_ID=33770'),
      ox('건강을 위해 누구에게나 안전하다고 보장되는 음주량이 명확히 정해져 있다.', 'X',
        'WHO와 질병관리청 자료는 음주에 대해 \'안전한 음주량\'으로 단정하기 어렵다는 관점을 제시합니다.',
        'https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=5297'),
      mc('알코올 1g당 열량으로 가장 적절한 것은?',
        ['약 7kcal', '약 1kcal', '약 3kcal', '약 12kcal'], 0,
        '알코올은 1g당 약 7kcal로 열량이 높고 영양소 대사를 방해할 수 있습니다.',
        'http://www.samsunghospital.com/home/healthInfo/content/contenView.do?CONT_CLS_CD=001021005003&CONT_ID=6352&CONT_SRC=HOMEPAGE&CONT_SRC_ID=33770'),
      sa('운동 목표가 있을 때 술자리에서 실천할 수 있는 절주 행동을 2가지 적으세요.',
        '예: 마실 양을 미리 정하기, 무알코올 음료 선택, 운동 전후 음주 피하기, 물을 함께 마시기, 권유 거절 문장 준비',
        '절주는 운동 회복, 체중관리, 암 예방 측면에서 모두 의미가 있습니다.',
        'https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=5297'),
    ],
  },
  {
    key: 'nutrition', title: '영양', emoji: '🥗', category: 'DIET',
    questions: [
      mc('근육합성을 고려한 단백질 섭취 방법으로 가장 적절한 것은?',
        ['하루 단백질을 끼니별로 나누어 섭취한다', '하루 단백질을 한 번에 몰아서 먹는다', '보충제만 먹고 일반식은 줄인다', '운동하지 않는 날에는 단백질이 전혀 필요 없다'], 0,
        '한 번에 활용 가능한 단백질 양에는 한계가 있어 끼니별 분할 섭취가 유리합니다.',
        'https://www.k-health.com/news/articleView.html?idxno=88625'),
      ox('고단백 식단을 장기간 과도하게 유지하면 신장에 부담이 될 수 있다.', 'O',
        '특히 기존 신장질환 위험이 있거나 과도한 단백질 섭취를 장기간 지속하면 주의가 필요합니다.',
        'https://www.k-health.com/news/articleView.html?idxno=88625'),
      ox('운동 효과를 높이려면 운동량뿐 아니라 식단의 질도 중요하다.', 'O',
        '초가공식품 위주 식사는 여러 건강위험과 관련되어 있어 식단 질 관리가 필요합니다.',
        'https://bmjgroup.com/consistent-evidence-links-ultra-processed-food-to-over-30-damaging-health-outcomes/'),
      mc('초가공식품을 많이 섭취하는 식습관과 관련성이 높은 건강위험으로 가장 적절한 것은?',
        ['심혈관질환·제2형당뇨·비만 위험 증가', '모든 질병 위험의 확실한 감소', '수면시간의 무조건 증가', '근력의 즉각적인 증가'], 0,
        '대규모 리뷰에서 초가공식품 섭취는 여러 불리한 건강결과와 관련되었습니다.',
        'https://bmjgroup.com/consistent-evidence-links-ultra-processed-food-to-over-30-damaging-health-outcomes/'),
      sa('PX나 편의점에서 초가공 간식을 줄이기 위해 선택할 수 있는 대체 식품을 2가지 적으세요.',
        '예: 삶은 달걀, 무가당 요거트, 견과류, 과일, 우유, 두유, 샐러드, 닭가슴살',
        '가공도가 낮고 단백질·식이섬유가 있는 식품으로 대체하면 식단 질 개선에 도움이 됩니다.',
        'https://bmjgroup.com/consistent-evidence-links-ultra-processed-food-to-over-30-damaging-health-outcomes/'),
    ],
  },
  {
    key: 'activity', title: '신체활동', emoji: '🏃', category: 'WALKING',
    questions: [
      mc('우울·불안 완화에 도움이 되는 운동으로 근거가 비교적 강하게 제시된 것은?',
        ['유산소 운동', '밤샘 게임', '장시간 앉아 있기', '운동을 완전히 피하기'], 0,
        '운동은 우울·불안 증상 완화에 도움이 될 수 있지만, 연구 한계도 함께 고려해야 합니다.',
        'https://bmjgroup.com/aerobic-exercise-may-be-most-effective-for-relieving-depression-anxiety-symptoms/'),
      ox('근육통이 오래 지속될수록 근성장이 더 잘 된다는 뜻이다.', 'X',
        '근육통은 회복 과정의 신호일 수 있지만 근성장의 크기를 그대로 의미하지는 않습니다.',
        'https://www.stcarollo.or.kr/0401/5588'),
      ox('운동 후 48시간 정도 회복했는데도 일주일 내내 운동을 쉬어야만 효과가 있다.', 'X',
        '회복 상태에 따라 조절해야 하며, 무조건 장기간 쉬는 것이 효율적이라고 볼 수는 없습니다.',
        'https://www.stcarollo.or.kr/0401/5588'),
      mc('성인 신체활동 권장량으로 가장 적절한 것은?',
        ['주당 중강도 150분 또는 고강도 75분 + 근력운동 주 2회 이상', '월 1회 10분 걷기', '근력운동만 매일 3시간', '숨이 찰 정도의 운동은 모두 금지'], 0,
        '성인은 유산소 활동과 근력운동을 함께 실천하는 것이 권장됩니다.',
        'https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=5293'),
      sa('스트레스가 높을 때 바로 실천할 수 있는 신체활동 한 가지를 적으세요.',
        '예: 10분 걷기, 계단 오르기, 가벼운 조깅, 스트레칭, 팔굽혀펴기, 스쿼트',
        '짧은 활동도 기분 전환과 스트레스 완화에 도움이 될 수 있습니다.',
        'https://bmjgroup.com/aerobic-exercise-may-be-most-effective-for-relieving-depression-anxiety-symptoms/'),
    ],
  },
  {
    key: 'oral', title: '구강건강', emoji: '🦷', category: 'ETC',
    questions: [
      ox('흡연·커피로 생긴 치아 착색은 양치만으로 항상 원래 색으로 완전히 돌아온다.', 'X',
        '착색·변색은 양치만으로 해결되지 않을 수 있으며 전문 관리가 필요할 수 있습니다.',
        'https://www.k-health.com/news/articleView.html?idxno=22209'),
      ox('흡연과 혀 백태는 구취와 관련될 수 있어 혀 닦기와 치실 사용도 중요하다.', 'O',
        '구취 관리는 칫솔질뿐 아니라 혀 관리, 치실 사용, 금연 등과 연결됩니다.',
        'https://www.k-health.com/news/articleView.html?idxno=22209'),
      ox('치주질환은 입 안 문제일 뿐 전신 건강과는 관련이 없다.', 'X',
        '치주질환은 심혈관질환·당뇨 등 전신 건강과의 관련성이 보고됩니다.',
        'https://www.kperio.org/patient/General.php'),
      mc('최근 외래 다빈도 상병에서 매우 높은 비중을 차지한 구강질환은?',
        ['치은염 및 치주질환', '손목 골절', '급성 맹장염', '색맹'], 0,
        '치은염·치주질환은 외래 진료에서 매우 흔한 질환입니다.',
        'https://www.seoul.co.kr/news/society/health-medical/2025/06/08/20250608500067'),
      sa('치주질환 예방을 위해 실천할 수 있는 행동을 2가지 적으세요.',
        '예: 올바른 칫솔질, 치실 사용, 혀 닦기, 정기 스케일링, 금연',
        '정기적인 구강관리와 스케일링은 치주질환 예방과 재발 방지에 중요합니다.',
        'https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=5718'),
    ],
  },
  {
    key: 'suicide', title: '자살예방', emoji: '💛', category: 'MINDCARE',
    questions: [
      ox('주변 사람이 힘들어 보일 때 위험신호를 보고, 이야기를 듣고, 필요한 도움으로 연결하는 것이 중요하다.', 'O',
        '게이트키퍼의 핵심은 위험신호 파악, 경청, 전문자원 연결입니다.',
        'https://edu.kfsp.or.kr/edu/common/greeting.do'),
      ox('자살 생각이 있는지 직접 물어보면 위험이 커지므로 절대 물어보면 안 된다.', 'X',
        '적절하게 직접 묻고 경청하는 것은 위험을 파악하고 도움을 연결하는 데 중요합니다.',
        'https://edu.kfsp.or.kr/edu/common/greeting.do'),
      mc('자살예방 상담전화 번호로 가장 적절한 것은?',
        ['109', '119', '1336', '120'], 0,
        '109는 자살예방 상담전화로 24시간 운영됩니다.',
        'https://www.129.go.kr/109'),
      mc('자살예방 게이트키퍼 교육의 핵심 흐름으로 가장 적절한 것은?',
        ['보고-듣고-말하기', '비난-설득-격리하기', '무시-회피-기다리기', '충고-판단-종결하기'], 0,
        '위험신호를 보고, 이야기를 듣고, 전문가나 도움 자원에 연결하는 흐름입니다.',
        'https://edu.kfsp.or.kr/edu/common/greeting.do'),
      sa('힘들 때 도움을 요청할 수 있는 사람이나 기관을 2가지 적으세요.',
        '예: 전우, 가족, 간부, 병영생활 전문상담관, 군종, 상담전화 109',
        '위기 상황 전에 도움 자원을 미리 정해두면 실제 도움 요청이 쉬워집니다.',
        'https://www.129.go.kr/109'),
    ],
  },
  {
    key: 'dementia', title: '치매', emoji: '🧠', category: 'ETC',
    questions: [
      ox('치매 예방은 노년기에만 의미가 있고, 젊을 때의 생활습관과는 관련이 없다.', 'X',
        '중년기 이전부터 운동, 금연, 절주, 사회활동 등 보호요인을 강화하는 것이 중요합니다.',
        'https://www.alzint.org/news-events/news/lancet-commission-identifies-two-new-risk-factors-for-dementia-and-suggests-45-of-cases-could-be-delayed-or-reduced/'),
      mc('치매 예방을 위한 운동 습관으로 가장 적절한 것은?',
        ['주 5회 중강도 30분 또는 주 3회 고강도 20분 운동', '1년에 한 번만 운동하기', '운동은 뇌 건강과 무관하므로 하지 않기', '운동 대신 음주량 늘리기'], 0,
        '규칙적 운동은 뇌혈류 개선과 뇌 건강 유지에 도움이 될 수 있습니다.',
        'https://www.nhis.or.kr/static/alim/paper/oldpaper/202309/sub/section1_4.html'),
      ox('흡연과 과음은 인지장애·치매 위험과 관련될 수 있다.', 'O',
        '흡연과 과음은 인지기능 저하 위험요인으로 제시됩니다.',
        'https://www.nhis.or.kr/static/alim/paper/oldpaper/202309/sub/section1_4.html'),
      mc('Lancet Commission 2024에서 제시한 \'바꿀 수 있는 치매 위험요인\'의 수로 가장 적절한 것은?',
        ['14개', '2개', '100개', '0개'], 0,
        '교육, 운동, 흡연, 음주, 고혈압, 비만 등 14개 위험요인이 제시되었습니다.',
        'https://www.alzint.org/news-events/news/lancet-commission-identifies-two-new-risk-factors-for-dementia-and-suggests-45-of-cases-could-be-delayed-or-reduced/'),
      sa('치매 예방을 위해 생활 속에서 실천할 수 있는 행동을 3가지 적으세요.',
        '예: 규칙적 운동, 금연, 절주, 사회활동, 배움 지속, 혈압 관리',
        '치매 예방은 위험요인을 줄이고 보호요인을 강화하는 방향으로 접근합니다.',
        'https://www.alzint.org/news-events/news/lancet-commission-identifies-two-new-risk-factors-for-dementia-and-suggests-45-of-cases-could-be-delayed-or-reduced/'),
    ],
  },
  {
    key: 'addiction', title: '중독', emoji: '🎰', category: 'MINDCARE',
    questions: [
      mc('최근 군 내에서 휴대전화 사용과 함께 증가가 지적된 문제로 가장 적절한 것은?',
        ['사이버도박', '손씻기', '치실 사용', '독서량 증가'], 0,
        '군 내 사이버도박 관련 형사입건 증가가 보도되었습니다.',
        'https://www.seoul.co.kr/news/politics/2024/09/30/20240930500208'),
      ox('불법도박은 단순 장난이므로 형사처벌이나 군 징계와는 관련이 없다.', 'X',
        '불법도박은 법적 처벌과 징계로 이어질 수 있습니다.',
        'https://www.lawissue.co.kr/view.php?ud=202410021204541666cf2d78c68_12'),
      ox('온라인 환경은 도박이나 마약류 접근성을 높일 수 있어 주의가 필요하다.', 'O',
        '스마트폰·온라인 접근성 증가는 중독 문제의 위험요인으로 지적됩니다.',
        'https://www.seoul.co.kr/news/politics/2024/09/30/20240930500208'),
      mc('도박문제 전문 도움을 받을 수 있는 헬프라인 번호로 가장 적절한 것은?',
        ['1336', '112', '129', '182'], 0,
        '1336은 도박문제 예방·치유 지원과 연계되는 상담 자원입니다.',
        'https://www.gov.kr/portal/service/serviceInfo/137100000173'),
      sa('도박 충동이 생겼을 때 취할 수 있는 안전한 행동을 2가지 적으세요.',
        '예: 도박 사이트 차단, 결제수단 차단, 상담 요청, 신뢰하는 사람에게 알리기, 1336 연락',
        '중독은 혼자 끊기 어려울 수 있어 조기 도움 요청이 중요합니다.',
        'https://www.gov.kr/portal/service/serviceInfo/137100000173'),
    ],
  },
  {
    key: 'community_mental', title: '지역사회정신건강', emoji: '🧘', category: 'MINDCARE',
    questions: [
      ox('전국민 마음투자 지원사업은 정서적 어려움이 있는 국민에게 전문 심리상담 바우처를 지원한다.', 'O',
        '전문 심리상담 바우처를 통해 조기 개입을 지원하는 제도입니다.',
        'https://www.socialservice.or.kr:444/user/htmlEditor/view2.do?p_sn=71'),
      ox('일부 청년 마음건강 지원사업은 의무복무 제대군인에게 군 복무기간에 따른 연령 연장을 적용할 수 있다.', 'O',
        '서울시 공고 기준에서 의무복무 제대군인의 연령 연장 내용이 확인됩니다.',
        'https://news.seoul.go.kr/gov/archives/576372'),
      mc('마음이 힘들 때 도움 요청 대상으로 가장 적절한 것은?',
        ['병영생활 전문상담관·군종·상담전화 등', '아무에게도 말하지 않고 버티기', '문제를 모두 장난으로 넘기기', '수면을 줄이고 혼자 해결하기'], 0,
        '정신건강 문제는 혼자 참기보다 이용 가능한 자원을 연결하는 것이 중요합니다.',
        'https://www.129.go.kr/109'),
      ox('국가건강검진 정신건강검사 결과에 따라 심리상담 연계가 이루어질 수 있다.', 'O',
        'PHQ-9 등 정신건강검사 결과는 조기 발견과 상담 연계에 활용될 수 있습니다.',
        'https://www.socialservice.or.kr:444/user/htmlEditor/view2.do?p_sn=71'),
      sa('내가 실제로 도움을 요청할 수 있는 사람이나 기관을 2가지 적으세요.',
        '예: 가족, 친구, 전우, 간부, 상담관, 군종, 지역 정신건강복지센터, 상담전화',
        '도움 요청 대상을 구체적으로 적어두면 위기 때 접근 장벽이 낮아집니다.',
        'https://www.129.go.kr/109'),
    ],
  },
  {
    key: 'cancer', title: '암', emoji: '🎗️', category: 'ETC',
    questions: [
      ox('50세 미만 조기발병암은 1990년부터 2019년 사이 전 세계적으로 증가한 것으로 보고되었다.', 'O',
        'BMJ Oncology 분석에서 50세 미만 조기발병암 증가가 보고되었습니다.',
        'https://bmjgroup.com/global-surge-in-cancers-among-the-under-50s-over-past-three-decades/'),
      mc('조기발병암 위험요인으로 함께 언급되는 생활습관 조합으로 가장 적절한 것은?',
        ['식이, 음주, 흡연', '손톱 길이, 머리색, 혈액형', '하루 물컵 색깔, 신발 크기', '휴대폰 배경화면'], 0,
        '식이, 음주, 흡연은 바꿀 수 있는 암 위험요인으로 자주 언급됩니다.',
        'https://bmjgroup.com/global-surge-in-cancers-among-the-under-50s-over-past-three-decades/'),
      ox('알코올은 1군 발암물질로 분류되며 여러 암 위험과 관련될 수 있다.', 'O',
        '알코올 대사산물인 아세트알데히드는 구강, 식도, 대장, 유방 등 여러 암 위험과 관련됩니다.',
        'https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=5297'),
      mc('한국 20·30대 연구에서 지방간과 관련해 보고된 내용으로 가장 적절한 것은?',
        ['50세 미만 조기 암 위험 증가와 관련될 수 있다', '암 위험을 반드시 0으로 낮춘다', '생활습관과 무관하다', '젊은 층에서는 의미가 없다'], 0,
        '젊은 지방간 환자에서 50세 미만 조기 암 위험 증가가 보고되었습니다.',
        'https://biz.heraldcorp.com/article/10581509'),
      sa('암 예방을 위해 바꿀 수 있는 생활습관을 2가지 적으세요.',
        '예: 금연, 절주, 규칙적 운동, 체중관리, 균형 잡힌 식사',
        '암 예방은 바꿀 수 있는 위험요인을 줄이는 것에서 시작합니다.',
        'https://bmjgroup.com/global-surge-in-cancers-among-the-under-50s-over-past-three-decades/'),
    ],
  },
  {
    key: 'cardio', title: '심뇌혈관', emoji: '❤️', category: 'ETC',
    questions: [
      ox('20·30대도 고혈압 관리가 필요하며 생활습관의 영향을 받을 수 있다.', 'O',
        '청년층 고혈압도 증가 추세가 보고되며, 생활습관 관리가 중요합니다.',
        'https://edaily.co.kr/News/Read?mediaCodeNo=257&newsId=02584646645449576'),
      mc('고혈압이 \'침묵의 살인자\'라고 불리는 이유로 가장 적절한 것은?',
        ['대부분 뚜렷한 증상이 없어 측정 전까지 모를 수 있기 때문이다', '항상 심한 통증이 먼저 오기 때문이다', '젊은 사람에게는 절대 생기지 않기 때문이다', '운동하면 반드시 악화되기 때문이다'], 0,
        '고혈압은 무증상인 경우가 많아 정기 측정이 핵심입니다.',
        'https://www.rapportian.com/news/articleView.html?idxno=221168'),
      ox('짠 음식, 가공식품, 음주는 젊은 고혈압과 관련된 생활요인으로 볼 수 있다.', 'O',
        '나트륨 과다와 음주는 혈압 상승과 관련됩니다.',
        'https://edaily.co.kr/News/Read?mediaCodeNo=257&newsId=02584646645449576'),
      mc('20·30대 고혈압 관리의 문제점으로 가장 적절한 것은?',
        ['인지율·치료율·조절률이 낮아 관리 사각지대가 될 수 있다', '인지율이 100%라 문제가 없다', '치료가 필요 없는 연령대다', '혈압 측정이 전혀 불가능하다'], 0,
        '젊은 층은 고혈압을 알고 치료·조절하는 비율이 낮아 관리가 늦어질 수 있습니다.',
        'https://www.dailymedi.com/news/news_view.php?wr_id=918335'),
      sa('혈압 관리를 위해 실천할 수 있는 생활습관을 2가지 적으세요.',
        '예: 정기 혈압 측정, 나트륨 줄이기, 규칙적 운동, 절주, 체중관리, 금연',
        '젊을 때부터 혈압을 관리하면 장기적인 혈관 손상 누적을 줄이는 데 도움이 됩니다.',
        'https://www.rapportian.com/news/articleView.html?idxno=221168'),
    ],
  },
  {
    key: 'obesity', title: '비만', emoji: '⚖️', category: 'ETC',
    questions: [
      mc('급격한 감량이 요요로 이어질 수 있는 이유로 가장 적절한 것은?',
        ['지방과 근육이 함께 줄고 기초대사량이 낮아질 수 있기 때문이다', '근육량이 반드시 크게 증가하기 때문이다', '식욕이 영구적으로 사라지기 때문이다', '감량 후에는 에너지 섭취와 무관해지기 때문이다'], 0,
        '무리한 감량은 근육 손실과 기초대사량 저하를 유발해 체중 재증가 위험을 높일 수 있습니다.',
        'https://www.nhis.or.kr/magazin/146/html/sub2.html'),
      ox('무리한 단기 다이어트는 영양결핍, 부정맥, 면역저하 등 건강문제를 일으킬 수 있다.', 'O',
        '극단적 감량은 신체 기능 저하와 여러 건강문제를 유발할 수 있습니다.',
        'https://www.nhis.or.kr/magazin/146/html/sub2.html'),
      ox('체중 감량 후 다시 늘었다고 해서 무조건 포기해야 하며, 다시 관리해도 의미가 없다.', 'X',
        '요요 관련 근거에는 논쟁이 있지만, 감량을 포기하기보다 지속 가능한 관리로 재시도하는 것이 중요합니다.',
        'https://news.sbs.co.kr/news/endPage.do?news_id=N1007878152'),
      mc('같은 체중이라도 복부비만이 특히 중요한 이유로 가장 적절한 것은?',
        ['고혈압·당뇨·심뇌혈관질환 위험과 연결될 수 있기 때문이다', '키가 반드시 커지기 때문이다', '수면 시간이 항상 늘어나기 때문이다', '운동 능력을 무조건 높이기 때문이다'], 0,
        '내장지방형 비만은 대사질환과 심뇌혈관질환 위험과 관련됩니다.',
        'https://www.kmib.co.kr/article/view.asp?arcid=0029836998'),
      sa('건강한 체중관리를 위한 원칙을 2가지 적으세요.',
        '예: 서서히 감량하기, 굶지 않고 규칙적으로 먹기, 근력운동 병행, 단백질 섭취, 수면관리',
        '체중관리는 빠른 감량보다 지속 가능성과 근육 유지가 중요합니다.',
        'https://www.nhis.or.kr/magazin/146/html/sub2.html'),
    ],
  },
]

export const QUIZ_AUDIENCES = [
  {
    key: 'soldier_20s',
    label: '군인·20대 초반',
    emoji: '🪖',
    description: '군 장병·20대 초반 대상 건강 상식 (출처 검증 완료)',
    topics: TOPICS,
  },
]
